#!/usr/bin/env python3
"""
Generate the RGI emoji ZWJ sequence fixture the width/cluster tests walk.

Emits a data-only header holding every RGI_Emoji_ZWJ_Sequence from
emoji-zwj-sequences.txt, one sequence per line, separated by spaces (no
sequence contains U+0020, so splitting the blob on ' ' recovers them).
Invisible codepoints — ZWJ, variation selectors, format characters — are
written as \\uXXXX escapes so a sequence's joiners stay visible in the
source; everything else is written as its literal UTF-8.

The header carries the same provenance banner as unicode_tables.h: the UCD
file's version and SHA-256, this generator's SHA-256, and the exact command
line that produced it, so a stale fixture is visible at a glance.

Usage:
    python3 src/scripts/gen_zwj_sequences.py --out tests/zwj_sequences.h

    # Use a local copy of the file instead of downloading:
    python3 src/scripts/gen_zwj_sequences.py --ucd /path/to/emoji --out tests/zwj_sequences.h
"""

from __future__ import annotations

import argparse
import hashlib
import os
import re
import sys
import urllib.request

# emoji-zwj-sequences.txt lives under the emoji release tree, not under
# ucd/emoji/ with the other emoji data files.
ZWJ_URL = "https://www.unicode.org/Public/emoji/latest/emoji-zwj-sequences.txt"
ZWJ_RELPATH = "emoji-zwj-sequences.txt"

UCD_VERSION_LINE = re.compile(r"^#\s+Version:\s*(\S+)")
SEQ_LINE = re.compile(r"^([0-9A-Fa-f ]+)\s*;\s*(\S+)\s*;")

DEFAULT_PREFIX = "CFR_"
DEFAULT_GUARD = "COFFER_TEST_ZWJ_SEQUENCES_H"

# Codepoints written as escapes: control characters and the format
# characters that make a sequence unreadable in source.
ESCAPE_SINGLE = {
    0x22: '\\"',
    0x5C: "\\\\",
}
ESCAPE_SET = {
    0x00AD,  # soft hyphen
    0x200B, 0x200C, 0x200D, 0x200E, 0x200F,  # zero-width space .. RLM
    0x2028, 0x2029,  # line/paragraph separator
    0x202A, 0x202B, 0x202C, 0x202D, 0x202E,  # bidi embedding/override
    0x2060, 0x2061, 0x2062, 0x2063, 0x2064,  # word joiner .. invisible plus
    0x2066, 0x2067, 0x2068, 0x2069,  # bidi isolates
    0xFE0E, 0xFE0F,  # variation selectors 15/16
    0xFEFF,  # BOM
}


def is_escaped(cp: int) -> bool:
    return cp < 0x20 or 0x7F <= cp <= 0x9F or cp in ESCAPE_SET or cp in ESCAPE_SINGLE


def escape(cp: int) -> str:
    if cp in ESCAPE_SINGLE:
        return ESCAPE_SINGLE[cp]
    if cp <= 0xFFFF:
        return f"\\u{cp:04X}"
    return f"\\U{cp:08X}"


def load(ucd: str | None) -> bytes:
    if ucd:
        path = os.path.join(ucd, ZWJ_RELPATH)
        with open(path, "rb") as f:
            return f.read()
    print(f"Downloading {ZWJ_URL} ...", file=sys.stderr)
    with urllib.request.urlopen(ZWJ_URL) as resp:
        return resp.read()


def version(data: bytes) -> str:
    for line in data.decode("utf-8", "replace").splitlines()[:12]:
        m = UCD_VERSION_LINE.match(line)
        if m:
            return m.group(1)
    return "unknown"


def parse(data: bytes) -> list[list[int]]:
    """Every RGI_Emoji_ZWJ_Sequence, as a list of codepoint lists."""
    out: list[list[int]] = []
    for line in data.decode("utf-8", "replace").splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        m = SEQ_LINE.match(line)
        if not m or m.group(2) != "RGI_Emoji_ZWJ_Sequence":
            continue
        out.append([int(cp, 16) for cp in m.group(1).split()])
    return out


def emit(seqs: list[list[int]], prefix: str, guard: str, data: bytes,
         prog: str, ucd: str | None, out_path: str | None) -> str:
    gen_sha = hashlib.sha256(open(os.path.abspath(__file__), "rb").read()).hexdigest()[:16]
    data_sha = hashlib.sha256(data).hexdigest()[:16]
    ver = version(data)

    cmd = ["python3", prog]
    if ucd:
        cmd += ["--ucd", ucd]
    if prefix != DEFAULT_PREFIX:
        cmd += ["--prefix", prefix]
    if guard != DEFAULT_GUARD:
        cmd += ["--guard", guard]
    if out_path:
        cmd += ["--out", out_path]

    w = []
    w.append("/* Generated by gen_zwj_sequences.py — DO NOT EDIT BY HAND.\n")
    w.append(" *\n")
    w.append(f" * UCD source: {ZWJ_URL} (Emoji {ver})\n")
    w.append(f" *   {ZWJ_RELPATH:<38} {ver:<8} sha256 {data_sha}\n")
    w.append(f" *   {'gen_zwj_sequences.py':<38} {'':<8} sha256 {gen_sha}  (this generator)\n")
    w.append(" *\n")
    w.append(" * Regenerate:\n")
    w.append(f" *   {' '.join(cmd)}\n")
    w.append(" *\n")
    w.append(" * Every RGI_Emoji_ZWJ_Sequence, one per line, space-separated. ZWJ,\n")
    w.append(" * variation selectors and other format characters are escaped so the\n")
    w.append(" * joiners stay visible; the rest is literal UTF-8. No sequence contains\n")
    w.append(" * U+0020, so splitting the blob on ' ' recovers them.\n")
    w.append(" *\n")
    w.append(" * Data-only by design — the tests do the interpreting.\n")
    w.append(" */\n")
    w.append("\n")
    w.append(f"#ifndef {guard}\n")
    w.append(f"#define {guard}\n")
    w.append("\n")
    w.append(f"#define {prefix}ZWJ_SEQUENCE_COUNT {len(seqs)}\n")
    w.append("\n")
    w.append(f"static const char {prefix}ZWJ_SEQUENCES[] =\n")
    last = len(seqs) - 1
    for i, cps in enumerate(seqs):
        body = "".join(escape(cp) if is_escaped(cp) else chr(cp) for cp in cps)
        # The terminating semicolon rides the last literal so the file stays
        # clang-format clean (`make format` walks tests/*.h).
        w.append(f'    "{body} "{";" if i == last else ""}\n')
    w.append("\n")
    w.append(f"#endif /* {guard} */\n")
    return "".join(w)


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("--prefix", default=DEFAULT_PREFIX,
                    help=f"name prefix (default: {DEFAULT_PREFIX})")
    ap.add_argument("--guard", default=None,
                    help=f"include guard macro (default: {DEFAULT_GUARD})")
    ap.add_argument("--ucd", default=None,
                    help="directory holding emoji-zwj-sequences.txt instead of downloading")
    ap.add_argument("--out", default=None, help="write here instead of stdout")
    args = ap.parse_args(argv)
    guard = args.guard or DEFAULT_GUARD

    data = load(args.ucd)
    seqs = parse(data)
    if not seqs:
        print("ERROR: no RGI_Emoji_ZWJ_Sequence lines found", file=sys.stderr)
        return 1

    text = emit(seqs, args.prefix, guard, data, sys.argv[0], args.ucd, args.out)
    if args.out:
        with open(args.out, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
    else:
        sys.stdout.write(text)
    print(f"{len(seqs)} sequences (Emoji {version(data)})", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
